---
# master playbook
- hosts: all
  become: true
  gather_facts: false
  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup

- name: Install Docker
  hosts: all
  become: true
  roles:
    - { role: docker }
    - { role: docker-compose }

- name: Deploy media stack
  hosts: all
  become: true
  roles:
    - { role: media_stack }

- name: Deploy admin stack
  hosts: all
  become: true
  roles:
    - { role: admin_stack }