version: '3.4'

networks:
  traefik-net:
    external: true
  prometheus:

configs:
  alert.rules.yml:
    file: {{ prometheus_config_path }}/alert.rules.yml
  prometheus.yml:
    file: {{ prometheus_config_path }}/prometheus.yml

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: {{ prometheus_data_path }}
  alertmanager_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: {{ alertmanager_data_path }}
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: {{ grafana_data_path }}

services:
#####################################################################
### Prometheus ######################################################
#####################################################################
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus
      - traefik-net
    configs:
      - source: alert.rules.yml
        target: /etc/prometheus/alert.rules.yml
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    labels:
      - traefik.enable=true
      - traefik.port=9090
      - traefik.frontend.rule=Host:{{ default_host }}; PathPrefixStrip: /prometheus
      - traefik.docker.network=traefik-net

#####################################################################
### Alertmanager ####################################################
#####################################################################
  alertmanager: 
    image: prom/alertmanager
    volumes:
      - alertmanager:/alertmanager
    networks:
      - prometheus
      - traefik-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    networks:
      - prometheus
      - traefik-net
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/config.yml
    labels:
      - traefik.enable=true
      - traefik.port=9093
      - traefik.frontend.rule=Host:{{ default_host }}; PathPrefixStrip: /alertmanager
      - traefik.docker.network=traefik-net

#####################################################################
### Grafana #########################################################
#####################################################################
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER={{ grafana_auth_user }}
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_DOMAIN={{ default_host }}
      - GF_SERVER_ROOT_URL={{ base_url }}/grafana
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning/
    networks:
      - prometheus 
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:{{ default_host }}; PathPrefixStrip: /grafana
      - traefik.docker.network=traefik-net

#####################################################################
### CAdvisor ########################################################
#####################################################################
  cadvisor:
    image: google/cadvisor
    #command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - prometheus

#####################################################################
### Node Exporter ###################################################
#####################################################################
  node-exporter:
    image: stefanprodan/swarmprom-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command: 
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    environment:
      - NODE_ID={{ '{{' }}.Node.ID{{ '}}' }}
    networks:
      - prometheus

#####################################################################
### Docker Exporter #################################################
#####################################################################
  docker-exporter:
    image: basi/socat
    networks:
      - prometheus
