debug = false
logLevel = "info"

defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[accessLog]
format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.auth]
    headerField = "X-WebAuth-User"
      [entryPoints.https.auth.basic]
      users = ["gberdayes:$apr1$U0asI9FY$vWcRefUyCLnSvB53i319b0", "admin:$apr1$y/waexQa$F3kF5bXpnD.XlCgzloZxT1", "jtoumelin:$apr1$jKBb97qY$FCSDG9tU2yWTfdx5IcEqQ/", "tlumineau:$apr1$kSf8AotH$0x4rQl9ly115h73nwt9Cv/", "lchamoin:$apr1$Y/St4s6z$bG7jWTzEByyMqq4.wf0RC0"]
    [entryPoints.https.tls]

[docker]
domain = "{{ app_domain }}"
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "{{ admin_email }}"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
  
[metrics]
  [metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.1,0.3,1.2,5.0]
