---
- name: Ensure Pip is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - python-dev
      - python-pip

- name: Ensure Docker py, Docker compose is installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - pip
    - docker
    - docker-compose

- name: Install bash-completion for Docker compose
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.18.0/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
