---
# Docker
- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - bash-completion

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
    state: present
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Enable service docker
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: restarted
